services:
    weewx:
        #image: tfilo/weewx:latest
        build: .
        container_name: weewx
        restart: unless-stopped
        environment:
           - LANG=de_DE.UTF-8
           - LC_ALL=de_DE.UTF-8
           - TZ=Europe/Vienna
        volumes:
            - ./data:/root/weewx-data:rw
            - ./html:/root/weewx-html:rw

#    nginx:
#        image: nginx
#        restart: unless-stopped
#        volumes:
#            - ./html:/usr/share/nginx/html:ro
#        ports:
#            - '8080:80'
